bazarr: remove server start test due to github API rate limiting issue
error message would be as below for server start

```
Bazarr starting...
2023-08-08 14:04:51,926 - root                             (10e0c8e00) :  ERROR (check_update:25) - Error trying to get releases from Github. Http error.
2023-08-08 14:04:54,155 - root                             (10e0c8e00) :  ERROR (check_update:25) - Error trying to get releases from Github. Http error.
Traceback (most recent call last):
  File "/usr/local/Cellar/bazarr/1.2.4/libexec/bazarr/main.py", line 35, in <module>
    check_if_new_update()
  File "/usr/local/Cellar/bazarr/1.2.4/libexec/bazarr/app/check_update.py", line 62, in check_if_new_update
    with open(os.path.join(args.config_dir, 'config', 'releases.txt'), 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/bazarr-test-20230808-7412-y55jsd/config/releases.txt'
Bazarr exited.
```

Signed-off-by: Rui Chen <rui@chenrui.dev>